"""
Markdown Report Generator for AutoResearcher AI
Generates clean, readable Markdown reports from research results.
"""


def generate_markdown_report(query: str, result: dict) -> str:
    """
    Generate a Markdown report from research results.
    
    Args:
        query (str): The research query or URL
        result (dict): Research result containing raw, cleaned, summary, sources, and integration_status
        
    Returns:
        str: Formatted Markdown document
    """
    # Extract data from result
    summary = result.get("summary", "No summary available")
    cleaned = result.get("cleaned", "No cleaned text available")
    raw = result.get("raw", "No raw data available")
    sources = result.get("sources", [])
    integration_status = result.get("integration_status", {})
    
    # Truncate raw data to first 2000 characters
    raw_truncated = raw[:2000]
    if len(raw) > 2000:
        raw_truncated += "\n\n... (truncated)"
    
    # Build Markdown document
    markdown = f"""# AutoResearcher AI Report

## Query
{query}

## Summary
{summary}

## Cleaned Text
{cleaned}

## Raw Crawl Data (truncated)
{raw_truncated}

## Sources
"""
    
    # Add sources as bullet list
    if sources:
        for source in sources:
            markdown += f"- {source}\n"
    else:
        markdown += "- No sources available\n"
    
    # Add integration status
    markdown += "\n## Integration Status\n"
    markdown += f"- Apify enabled: {integration_status.get('apify_enabled', False)}\n"
    markdown += f"- LLM enabled: {integration_status.get('llm_enabled', False)}\n"
    markdown += f"- LLM provider: {integration_status.get('llm_provider', 'none')}\n"
    
    # Add generation metadata
    from datetime import datetime
    markdown += f"\n---\n*Generated by AutoResearcher AI on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*\n"
    
    return markdown
